--1.Task

SELECT COUNTRY_TXT AS ZEME
    , DATE_FROM_PARTS(IYEAR, IMONTH, IDAY) AS DATUM 
    , CAST(RIGHT (EVENTID, 4)AS INT)   AS POCET_UTOKU
    , (NKILL - NKILLTER) AS POCET_ZABITYCH_OBETI
    , NKILLTER AS POCET_ZABITYCH_TERORISTU
    , NWOUND AS POCET_ZRANENYCH
FROM TEROR
WHERE IYEAR = 2015 AND  COUNTRY_TXT IN ('Iraq', 'Nigeria', 'Syria') AND POCET_UTOKU >= 10 AND POCET_ZABITYCH_OBETI >=8
ORDER BY ZEME, DATUM ASC;


--2.Task

SELECT COUNTRY_TXT AS ZEME
    , CAST(RIGHT (EVENTID, 4)AS INT)   AS POCET_UTOKU
    , (NKILL - NKILLTER) AS POCET_ZABITYCH_OBETI  
--    , DISTANCE
--    , IYEAR
    ,  CASE
         WHEN DISTANCE < 100  THEN '0-99 km'
         WHEN DISTANCE < 500 THEN '100-499 km'
         WHEN DISTANCE < 1000 THEN '500-999 km'
         WHEN DISTANCE > 1000 THEN '1000+ km'
         ELSE 'exact location unknown'
       END AS VZDALENOST_OD_PRAHY
FROM (
    SELECT COUNTRY_TXT
    , EVENTID
    , IYEAR
    , NKILL
    , NKILLTER
    , ST_DISTANCE( 
            ST_MAKEPOINT(LONGITUDE, LATITUDE),
            ST_MAKEPOINT(14.4378, 50.0755)
        ) / 1000  AS DISTANCE -- vzdálenost útoků od Prahy
    FROM TEROR)
WHERE IYEAR IN (2014,2015)
ORDER BY POCET_UTOKU DESC;


--3.Task

SELECT
      EVENTID
    , IYEAR
    , COUNTRY_TXT
    , CITY
    , ATTACKTYPE1_TXT
    , TARGTYPE1_TXT
    , GNAME
    , WEAPTYPE1_TXT
    , NKILL
FROM TEROR
WHERE COUNTRY_TXT IN ('IRAQ', 'AFGHANISTAN', 'PAKISTAN', 'NIGERIA') 
    AND NKILL >0 
    AND (TARGTYPE1_TXT !='PRIVATE CITIZENS & PROPERTY' 
    OR GNAME ='TALIBAN')
ORDER BY NKILL DESC     
LIMIT 15;
